/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift.messageservice;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserTopic implements org.apache.thrift.TBase<UserTopic, UserTopic._Fields>, java.io.Serializable, Cloneable, Comparable<UserTopic> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserTopic");

  private static final org.apache.thrift.protocol.TField ARCHIEVED_FIELD_DESC = new org.apache.thrift.protocol.TField("archieved", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField UNLIKES_FIELD_DESC = new org.apache.thrift.protocol.TField("unlikes", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField LIKES_FIELD_DESC = new org.apache.thrift.protocol.TField("likes", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField NOT_INTRESTED_FIELD_DESC = new org.apache.thrift.protocol.TField("notIntrested", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField LAST_READ_MESSAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("lastReadMessageId", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField LAST_WROTE_MEESSGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("lastWroteMeessgeId", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField ISREAD_FIELD_DESC = new org.apache.thrift.protocol.TField("isread", org.apache.thrift.protocol.TType.BOOL, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserTopicStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserTopicTupleSchemeFactory());
  }

  public boolean archieved; // required
  public boolean unlikes; // required
  public boolean likes; // required
  public boolean notIntrested; // required
  public long lastReadMessageId; // required
  public long lastWroteMeessgeId; // required
  public boolean isread; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ARCHIEVED((short)1, "archieved"),
    UNLIKES((short)2, "unlikes"),
    LIKES((short)3, "likes"),
    NOT_INTRESTED((short)4, "notIntrested"),
    LAST_READ_MESSAGE_ID((short)5, "lastReadMessageId"),
    LAST_WROTE_MEESSGE_ID((short)6, "lastWroteMeessgeId"),
    ISREAD((short)7, "isread");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ARCHIEVED
          return ARCHIEVED;
        case 2: // UNLIKES
          return UNLIKES;
        case 3: // LIKES
          return LIKES;
        case 4: // NOT_INTRESTED
          return NOT_INTRESTED;
        case 5: // LAST_READ_MESSAGE_ID
          return LAST_READ_MESSAGE_ID;
        case 6: // LAST_WROTE_MEESSGE_ID
          return LAST_WROTE_MEESSGE_ID;
        case 7: // ISREAD
          return ISREAD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ARCHIEVED_ISSET_ID = 0;
  private static final int __UNLIKES_ISSET_ID = 1;
  private static final int __LIKES_ISSET_ID = 2;
  private static final int __NOTINTRESTED_ISSET_ID = 3;
  private static final int __LASTREADMESSAGEID_ISSET_ID = 4;
  private static final int __LASTWROTEMEESSGEID_ISSET_ID = 5;
  private static final int __ISREAD_ISSET_ID = 6;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ARCHIEVED, new org.apache.thrift.meta_data.FieldMetaData("archieved", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.UNLIKES, new org.apache.thrift.meta_data.FieldMetaData("unlikes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.LIKES, new org.apache.thrift.meta_data.FieldMetaData("likes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.NOT_INTRESTED, new org.apache.thrift.meta_data.FieldMetaData("notIntrested", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.LAST_READ_MESSAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("lastReadMessageId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LAST_WROTE_MEESSGE_ID, new org.apache.thrift.meta_data.FieldMetaData("lastWroteMeessgeId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ISREAD, new org.apache.thrift.meta_data.FieldMetaData("isread", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserTopic.class, metaDataMap);
  }

  public UserTopic() {
  }

  public UserTopic(
    boolean archieved,
    boolean unlikes,
    boolean likes,
    boolean notIntrested,
    long lastReadMessageId,
    long lastWroteMeessgeId,
    boolean isread)
  {
    this();
    this.archieved = archieved;
    setArchievedIsSet(true);
    this.unlikes = unlikes;
    setUnlikesIsSet(true);
    this.likes = likes;
    setLikesIsSet(true);
    this.notIntrested = notIntrested;
    setNotIntrestedIsSet(true);
    this.lastReadMessageId = lastReadMessageId;
    setLastReadMessageIdIsSet(true);
    this.lastWroteMeessgeId = lastWroteMeessgeId;
    setLastWroteMeessgeIdIsSet(true);
    this.isread = isread;
    setIsreadIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserTopic(UserTopic other) {
    __isset_bitfield = other.__isset_bitfield;
    this.archieved = other.archieved;
    this.unlikes = other.unlikes;
    this.likes = other.likes;
    this.notIntrested = other.notIntrested;
    this.lastReadMessageId = other.lastReadMessageId;
    this.lastWroteMeessgeId = other.lastWroteMeessgeId;
    this.isread = other.isread;
  }

  public UserTopic deepCopy() {
    return new UserTopic(this);
  }

  @Override
  public void clear() {
    setArchievedIsSet(false);
    this.archieved = false;
    setUnlikesIsSet(false);
    this.unlikes = false;
    setLikesIsSet(false);
    this.likes = false;
    setNotIntrestedIsSet(false);
    this.notIntrested = false;
    setLastReadMessageIdIsSet(false);
    this.lastReadMessageId = 0;
    setLastWroteMeessgeIdIsSet(false);
    this.lastWroteMeessgeId = 0;
    setIsreadIsSet(false);
    this.isread = false;
  }

  public boolean isArchieved() {
    return this.archieved;
  }

  public UserTopic setArchieved(boolean archieved) {
    this.archieved = archieved;
    setArchievedIsSet(true);
    return this;
  }

  public void unsetArchieved() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ARCHIEVED_ISSET_ID);
  }

  /** Returns true if field archieved is set (has been assigned a value) and false otherwise */
  public boolean isSetArchieved() {
    return EncodingUtils.testBit(__isset_bitfield, __ARCHIEVED_ISSET_ID);
  }

  public void setArchievedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ARCHIEVED_ISSET_ID, value);
  }

  public boolean isUnlikes() {
    return this.unlikes;
  }

  public UserTopic setUnlikes(boolean unlikes) {
    this.unlikes = unlikes;
    setUnlikesIsSet(true);
    return this;
  }

  public void unsetUnlikes() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UNLIKES_ISSET_ID);
  }

  /** Returns true if field unlikes is set (has been assigned a value) and false otherwise */
  public boolean isSetUnlikes() {
    return EncodingUtils.testBit(__isset_bitfield, __UNLIKES_ISSET_ID);
  }

  public void setUnlikesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UNLIKES_ISSET_ID, value);
  }

  public boolean isLikes() {
    return this.likes;
  }

  public UserTopic setLikes(boolean likes) {
    this.likes = likes;
    setLikesIsSet(true);
    return this;
  }

  public void unsetLikes() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LIKES_ISSET_ID);
  }

  /** Returns true if field likes is set (has been assigned a value) and false otherwise */
  public boolean isSetLikes() {
    return EncodingUtils.testBit(__isset_bitfield, __LIKES_ISSET_ID);
  }

  public void setLikesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LIKES_ISSET_ID, value);
  }

  public boolean isNotIntrested() {
    return this.notIntrested;
  }

  public UserTopic setNotIntrested(boolean notIntrested) {
    this.notIntrested = notIntrested;
    setNotIntrestedIsSet(true);
    return this;
  }

  public void unsetNotIntrested() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NOTINTRESTED_ISSET_ID);
  }

  /** Returns true if field notIntrested is set (has been assigned a value) and false otherwise */
  public boolean isSetNotIntrested() {
    return EncodingUtils.testBit(__isset_bitfield, __NOTINTRESTED_ISSET_ID);
  }

  public void setNotIntrestedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NOTINTRESTED_ISSET_ID, value);
  }

  public long getLastReadMessageId() {
    return this.lastReadMessageId;
  }

  public UserTopic setLastReadMessageId(long lastReadMessageId) {
    this.lastReadMessageId = lastReadMessageId;
    setLastReadMessageIdIsSet(true);
    return this;
  }

  public void unsetLastReadMessageId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTREADMESSAGEID_ISSET_ID);
  }

  /** Returns true if field lastReadMessageId is set (has been assigned a value) and false otherwise */
  public boolean isSetLastReadMessageId() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTREADMESSAGEID_ISSET_ID);
  }

  public void setLastReadMessageIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTREADMESSAGEID_ISSET_ID, value);
  }

  public long getLastWroteMeessgeId() {
    return this.lastWroteMeessgeId;
  }

  public UserTopic setLastWroteMeessgeId(long lastWroteMeessgeId) {
    this.lastWroteMeessgeId = lastWroteMeessgeId;
    setLastWroteMeessgeIdIsSet(true);
    return this;
  }

  public void unsetLastWroteMeessgeId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTWROTEMEESSGEID_ISSET_ID);
  }

  /** Returns true if field lastWroteMeessgeId is set (has been assigned a value) and false otherwise */
  public boolean isSetLastWroteMeessgeId() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTWROTEMEESSGEID_ISSET_ID);
  }

  public void setLastWroteMeessgeIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTWROTEMEESSGEID_ISSET_ID, value);
  }

  public boolean isIsread() {
    return this.isread;
  }

  public UserTopic setIsread(boolean isread) {
    this.isread = isread;
    setIsreadIsSet(true);
    return this;
  }

  public void unsetIsread() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISREAD_ISSET_ID);
  }

  /** Returns true if field isread is set (has been assigned a value) and false otherwise */
  public boolean isSetIsread() {
    return EncodingUtils.testBit(__isset_bitfield, __ISREAD_ISSET_ID);
  }

  public void setIsreadIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISREAD_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ARCHIEVED:
      if (value == null) {
        unsetArchieved();
      } else {
        setArchieved((Boolean)value);
      }
      break;

    case UNLIKES:
      if (value == null) {
        unsetUnlikes();
      } else {
        setUnlikes((Boolean)value);
      }
      break;

    case LIKES:
      if (value == null) {
        unsetLikes();
      } else {
        setLikes((Boolean)value);
      }
      break;

    case NOT_INTRESTED:
      if (value == null) {
        unsetNotIntrested();
      } else {
        setNotIntrested((Boolean)value);
      }
      break;

    case LAST_READ_MESSAGE_ID:
      if (value == null) {
        unsetLastReadMessageId();
      } else {
        setLastReadMessageId((Long)value);
      }
      break;

    case LAST_WROTE_MEESSGE_ID:
      if (value == null) {
        unsetLastWroteMeessgeId();
      } else {
        setLastWroteMeessgeId((Long)value);
      }
      break;

    case ISREAD:
      if (value == null) {
        unsetIsread();
      } else {
        setIsread((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ARCHIEVED:
      return Boolean.valueOf(isArchieved());

    case UNLIKES:
      return Boolean.valueOf(isUnlikes());

    case LIKES:
      return Boolean.valueOf(isLikes());

    case NOT_INTRESTED:
      return Boolean.valueOf(isNotIntrested());

    case LAST_READ_MESSAGE_ID:
      return Long.valueOf(getLastReadMessageId());

    case LAST_WROTE_MEESSGE_ID:
      return Long.valueOf(getLastWroteMeessgeId());

    case ISREAD:
      return Boolean.valueOf(isIsread());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ARCHIEVED:
      return isSetArchieved();
    case UNLIKES:
      return isSetUnlikes();
    case LIKES:
      return isSetLikes();
    case NOT_INTRESTED:
      return isSetNotIntrested();
    case LAST_READ_MESSAGE_ID:
      return isSetLastReadMessageId();
    case LAST_WROTE_MEESSGE_ID:
      return isSetLastWroteMeessgeId();
    case ISREAD:
      return isSetIsread();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserTopic)
      return this.equals((UserTopic)that);
    return false;
  }

  public boolean equals(UserTopic that) {
    if (that == null)
      return false;

    boolean this_present_archieved = true;
    boolean that_present_archieved = true;
    if (this_present_archieved || that_present_archieved) {
      if (!(this_present_archieved && that_present_archieved))
        return false;
      if (this.archieved != that.archieved)
        return false;
    }

    boolean this_present_unlikes = true;
    boolean that_present_unlikes = true;
    if (this_present_unlikes || that_present_unlikes) {
      if (!(this_present_unlikes && that_present_unlikes))
        return false;
      if (this.unlikes != that.unlikes)
        return false;
    }

    boolean this_present_likes = true;
    boolean that_present_likes = true;
    if (this_present_likes || that_present_likes) {
      if (!(this_present_likes && that_present_likes))
        return false;
      if (this.likes != that.likes)
        return false;
    }

    boolean this_present_notIntrested = true;
    boolean that_present_notIntrested = true;
    if (this_present_notIntrested || that_present_notIntrested) {
      if (!(this_present_notIntrested && that_present_notIntrested))
        return false;
      if (this.notIntrested != that.notIntrested)
        return false;
    }

    boolean this_present_lastReadMessageId = true;
    boolean that_present_lastReadMessageId = true;
    if (this_present_lastReadMessageId || that_present_lastReadMessageId) {
      if (!(this_present_lastReadMessageId && that_present_lastReadMessageId))
        return false;
      if (this.lastReadMessageId != that.lastReadMessageId)
        return false;
    }

    boolean this_present_lastWroteMeessgeId = true;
    boolean that_present_lastWroteMeessgeId = true;
    if (this_present_lastWroteMeessgeId || that_present_lastWroteMeessgeId) {
      if (!(this_present_lastWroteMeessgeId && that_present_lastWroteMeessgeId))
        return false;
      if (this.lastWroteMeessgeId != that.lastWroteMeessgeId)
        return false;
    }

    boolean this_present_isread = true;
    boolean that_present_isread = true;
    if (this_present_isread || that_present_isread) {
      if (!(this_present_isread && that_present_isread))
        return false;
      if (this.isread != that.isread)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(UserTopic other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetArchieved()).compareTo(other.isSetArchieved());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArchieved()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.archieved, other.archieved);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUnlikes()).compareTo(other.isSetUnlikes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUnlikes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.unlikes, other.unlikes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLikes()).compareTo(other.isSetLikes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLikes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.likes, other.likes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNotIntrested()).compareTo(other.isSetNotIntrested());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNotIntrested()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.notIntrested, other.notIntrested);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastReadMessageId()).compareTo(other.isSetLastReadMessageId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastReadMessageId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastReadMessageId, other.lastReadMessageId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastWroteMeessgeId()).compareTo(other.isSetLastWroteMeessgeId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastWroteMeessgeId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastWroteMeessgeId, other.lastWroteMeessgeId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsread()).compareTo(other.isSetIsread());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsread()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isread, other.isread);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserTopic(");
    boolean first = true;

    sb.append("archieved:");
    sb.append(this.archieved);
    first = false;
    if (!first) sb.append(", ");
    sb.append("unlikes:");
    sb.append(this.unlikes);
    first = false;
    if (!first) sb.append(", ");
    sb.append("likes:");
    sb.append(this.likes);
    first = false;
    if (!first) sb.append(", ");
    sb.append("notIntrested:");
    sb.append(this.notIntrested);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastReadMessageId:");
    sb.append(this.lastReadMessageId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastWroteMeessgeId:");
    sb.append(this.lastWroteMeessgeId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isread:");
    sb.append(this.isread);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserTopicStandardSchemeFactory implements SchemeFactory {
    public UserTopicStandardScheme getScheme() {
      return new UserTopicStandardScheme();
    }
  }

  private static class UserTopicStandardScheme extends StandardScheme<UserTopic> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserTopic struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ARCHIEVED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.archieved = iprot.readBool();
              struct.setArchievedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UNLIKES
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.unlikes = iprot.readBool();
              struct.setUnlikesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LIKES
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.likes = iprot.readBool();
              struct.setLikesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NOT_INTRESTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.notIntrested = iprot.readBool();
              struct.setNotIntrestedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LAST_READ_MESSAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastReadMessageId = iprot.readI64();
              struct.setLastReadMessageIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // LAST_WROTE_MEESSGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastWroteMeessgeId = iprot.readI64();
              struct.setLastWroteMeessgeIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ISREAD
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isread = iprot.readBool();
              struct.setIsreadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserTopic struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ARCHIEVED_FIELD_DESC);
      oprot.writeBool(struct.archieved);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UNLIKES_FIELD_DESC);
      oprot.writeBool(struct.unlikes);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LIKES_FIELD_DESC);
      oprot.writeBool(struct.likes);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NOT_INTRESTED_FIELD_DESC);
      oprot.writeBool(struct.notIntrested);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_READ_MESSAGE_ID_FIELD_DESC);
      oprot.writeI64(struct.lastReadMessageId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_WROTE_MEESSGE_ID_FIELD_DESC);
      oprot.writeI64(struct.lastWroteMeessgeId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ISREAD_FIELD_DESC);
      oprot.writeBool(struct.isread);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserTopicTupleSchemeFactory implements SchemeFactory {
    public UserTopicTupleScheme getScheme() {
      return new UserTopicTupleScheme();
    }
  }

  private static class UserTopicTupleScheme extends TupleScheme<UserTopic> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserTopic struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetArchieved()) {
        optionals.set(0);
      }
      if (struct.isSetUnlikes()) {
        optionals.set(1);
      }
      if (struct.isSetLikes()) {
        optionals.set(2);
      }
      if (struct.isSetNotIntrested()) {
        optionals.set(3);
      }
      if (struct.isSetLastReadMessageId()) {
        optionals.set(4);
      }
      if (struct.isSetLastWroteMeessgeId()) {
        optionals.set(5);
      }
      if (struct.isSetIsread()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetArchieved()) {
        oprot.writeBool(struct.archieved);
      }
      if (struct.isSetUnlikes()) {
        oprot.writeBool(struct.unlikes);
      }
      if (struct.isSetLikes()) {
        oprot.writeBool(struct.likes);
      }
      if (struct.isSetNotIntrested()) {
        oprot.writeBool(struct.notIntrested);
      }
      if (struct.isSetLastReadMessageId()) {
        oprot.writeI64(struct.lastReadMessageId);
      }
      if (struct.isSetLastWroteMeessgeId()) {
        oprot.writeI64(struct.lastWroteMeessgeId);
      }
      if (struct.isSetIsread()) {
        oprot.writeBool(struct.isread);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserTopic struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.archieved = iprot.readBool();
        struct.setArchievedIsSet(true);
      }
      if (incoming.get(1)) {
        struct.unlikes = iprot.readBool();
        struct.setUnlikesIsSet(true);
      }
      if (incoming.get(2)) {
        struct.likes = iprot.readBool();
        struct.setLikesIsSet(true);
      }
      if (incoming.get(3)) {
        struct.notIntrested = iprot.readBool();
        struct.setNotIntrestedIsSet(true);
      }
      if (incoming.get(4)) {
        struct.lastReadMessageId = iprot.readI64();
        struct.setLastReadMessageIdIsSet(true);
      }
      if (incoming.get(5)) {
        struct.lastWroteMeessgeId = iprot.readI64();
        struct.setLastWroteMeessgeIdIsSet(true);
      }
      if (incoming.get(6)) {
        struct.isread = iprot.readBool();
        struct.setIsreadIsSet(true);
      }
    }
  }

}

