/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Building implements org.apache.thrift.TBase<Building, Building._Fields>, java.io.Serializable, Cloneable, Comparable<Building> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Building");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField ZIP_FIELD_DESC = new org.apache.thrift.protocol.TField("zip", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField STREET_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("streetId", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField FULL_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("fullNo", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BuildingStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BuildingTupleSchemeFactory());
  }

  public long id; // required
  public String zip; // required
  public long streetId; // required
  public String fullNo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    ZIP((short)2, "zip"),
    STREET_ID((short)3, "streetId"),
    FULL_NO((short)4, "fullNo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // ZIP
          return ZIP;
        case 3: // STREET_ID
          return STREET_ID;
        case 4: // FULL_NO
          return FULL_NO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __STREETID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ZIP, new org.apache.thrift.meta_data.FieldMetaData("zip", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STREET_ID, new org.apache.thrift.meta_data.FieldMetaData("streetId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FULL_NO, new org.apache.thrift.meta_data.FieldMetaData("fullNo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Building.class, metaDataMap);
  }

  public Building() {
  }

  public Building(
    long id,
    String zip,
    long streetId,
    String fullNo)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.zip = zip;
    this.streetId = streetId;
    setStreetIdIsSet(true);
    this.fullNo = fullNo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Building(Building other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetZip()) {
      this.zip = other.zip;
    }
    this.streetId = other.streetId;
    if (other.isSetFullNo()) {
      this.fullNo = other.fullNo;
    }
  }

  public Building deepCopy() {
    return new Building(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.zip = null;
    setStreetIdIsSet(false);
    this.streetId = 0;
    this.fullNo = null;
  }

  public long getId() {
    return this.id;
  }

  public Building setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public String getZip() {
    return this.zip;
  }

  public Building setZip(String zip) {
    this.zip = zip;
    return this;
  }

  public void unsetZip() {
    this.zip = null;
  }

  /** Returns true if field zip is set (has been assigned a value) and false otherwise */
  public boolean isSetZip() {
    return this.zip != null;
  }

  public void setZipIsSet(boolean value) {
    if (!value) {
      this.zip = null;
    }
  }

  public long getStreetId() {
    return this.streetId;
  }

  public Building setStreetId(long streetId) {
    this.streetId = streetId;
    setStreetIdIsSet(true);
    return this;
  }

  public void unsetStreetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STREETID_ISSET_ID);
  }

  /** Returns true if field streetId is set (has been assigned a value) and false otherwise */
  public boolean isSetStreetId() {
    return EncodingUtils.testBit(__isset_bitfield, __STREETID_ISSET_ID);
  }

  public void setStreetIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STREETID_ISSET_ID, value);
  }

  public String getFullNo() {
    return this.fullNo;
  }

  public Building setFullNo(String fullNo) {
    this.fullNo = fullNo;
    return this;
  }

  public void unsetFullNo() {
    this.fullNo = null;
  }

  /** Returns true if field fullNo is set (has been assigned a value) and false otherwise */
  public boolean isSetFullNo() {
    return this.fullNo != null;
  }

  public void setFullNoIsSet(boolean value) {
    if (!value) {
      this.fullNo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Long)value);
      }
      break;

    case ZIP:
      if (value == null) {
        unsetZip();
      } else {
        setZip((String)value);
      }
      break;

    case STREET_ID:
      if (value == null) {
        unsetStreetId();
      } else {
        setStreetId((Long)value);
      }
      break;

    case FULL_NO:
      if (value == null) {
        unsetFullNo();
      } else {
        setFullNo((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Long.valueOf(getId());

    case ZIP:
      return getZip();

    case STREET_ID:
      return Long.valueOf(getStreetId());

    case FULL_NO:
      return getFullNo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case ZIP:
      return isSetZip();
    case STREET_ID:
      return isSetStreetId();
    case FULL_NO:
      return isSetFullNo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Building)
      return this.equals((Building)that);
    return false;
  }

  public boolean equals(Building that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_zip = true && this.isSetZip();
    boolean that_present_zip = true && that.isSetZip();
    if (this_present_zip || that_present_zip) {
      if (!(this_present_zip && that_present_zip))
        return false;
      if (!this.zip.equals(that.zip))
        return false;
    }

    boolean this_present_streetId = true;
    boolean that_present_streetId = true;
    if (this_present_streetId || that_present_streetId) {
      if (!(this_present_streetId && that_present_streetId))
        return false;
      if (this.streetId != that.streetId)
        return false;
    }

    boolean this_present_fullNo = true && this.isSetFullNo();
    boolean that_present_fullNo = true && that.isSetFullNo();
    if (this_present_fullNo || that_present_fullNo) {
      if (!(this_present_fullNo && that_present_fullNo))
        return false;
      if (!this.fullNo.equals(that.fullNo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Building other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetZip()).compareTo(other.isSetZip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetZip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.zip, other.zip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStreetId()).compareTo(other.isSetStreetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStreetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.streetId, other.streetId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFullNo()).compareTo(other.isSetFullNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFullNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fullNo, other.fullNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Building(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("zip:");
    if (this.zip == null) {
      sb.append("null");
    } else {
      sb.append(this.zip);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("streetId:");
    sb.append(this.streetId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fullNo:");
    if (this.fullNo == null) {
      sb.append("null");
    } else {
      sb.append(this.fullNo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BuildingStandardSchemeFactory implements SchemeFactory {
    public BuildingStandardScheme getScheme() {
      return new BuildingStandardScheme();
    }
  }

  private static class BuildingStandardScheme extends StandardScheme<Building> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Building struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ZIP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.zip = iprot.readString();
              struct.setZipIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // STREET_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.streetId = iprot.readI64();
              struct.setStreetIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FULL_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fullNo = iprot.readString();
              struct.setFullNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Building struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.zip != null) {
        oprot.writeFieldBegin(ZIP_FIELD_DESC);
        oprot.writeString(struct.zip);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(STREET_ID_FIELD_DESC);
      oprot.writeI64(struct.streetId);
      oprot.writeFieldEnd();
      if (struct.fullNo != null) {
        oprot.writeFieldBegin(FULL_NO_FIELD_DESC);
        oprot.writeString(struct.fullNo);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BuildingTupleSchemeFactory implements SchemeFactory {
    public BuildingTupleScheme getScheme() {
      return new BuildingTupleScheme();
    }
  }

  private static class BuildingTupleScheme extends TupleScheme<Building> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Building struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetZip()) {
        optionals.set(1);
      }
      if (struct.isSetStreetId()) {
        optionals.set(2);
      }
      if (struct.isSetFullNo()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetZip()) {
        oprot.writeString(struct.zip);
      }
      if (struct.isSetStreetId()) {
        oprot.writeI64(struct.streetId);
      }
      if (struct.isSetFullNo()) {
        oprot.writeString(struct.fullNo);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Building struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.zip = iprot.readString();
        struct.setZipIsSet(true);
      }
      if (incoming.get(2)) {
        struct.streetId = iprot.readI64();
        struct.setStreetIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.fullNo = iprot.readString();
        struct.setFullNoIsSet(true);
      }
    }
  }

}

