/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GroupType implements org.apache.thrift.TEnum {
  NOBODY(0),
  FLAT(1),
  FLOOR(2),
  STAIRCASE(3),
  BUILDING(4),
  NEIGHBORS(5),
  BLOCK(6),
  DISTRICT(7),
  TOWN(8);

  private final int value;

  private GroupType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GroupType findByValue(int value) { 
    switch (value) {
      case 0:
        return NOBODY;
      case 1:
        return FLAT;
      case 2:
        return FLOOR;
      case 3:
        return STAIRCASE;
      case 4:
        return BUILDING;
      case 5:
        return NEIGHBORS;
      case 6:
        return BLOCK;
      case 7:
        return DISTRICT;
      case 8:
        return TOWN;
      default:
        return null;
    }
  }
}
