/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RelationsType implements org.apache.thrift.TEnum {
  MARRIED(0),
  NOTMARRIED(1),
  UNKNOWN(3);

  private final int value;

  private RelationsType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RelationsType findByValue(int value) { 
    switch (value) {
      case 0:
        return MARRIED;
      case 1:
        return NOTMARRIED;
      case 3:
        return UNKNOWN;
      default:
        return null;
    }
  }
}
