/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServiceType implements org.apache.thrift.TEnum {
  CountersEnabled(10),
  CountersConfirmed(11),
  CountersNotification(12);

  private final int value;

  private ServiceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServiceType findByValue(int value) { 
    switch (value) {
      case 10:
        return CountersEnabled;
      case 11:
        return CountersConfirmed;
      case 12:
        return CountersNotification;
      default:
        return null;
    }
  }
}
