/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserStatus implements org.apache.thrift.TEnum {
  UNCONFIRMED(0),
  CONFIRMED(1),
  REQUESTED(2),
  WAIT_CONFIRMATION(3),
  HIDE(4);

  private final int value;

  private UserStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return UNCONFIRMED;
      case 1:
        return CONFIRMED;
      case 2:
        return REQUESTED;
      case 3:
        return WAIT_CONFIRMATION;
      case 4:
        return HIDE;
      default:
        return null;
    }
  }
}
