/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserInterests implements org.apache.thrift.TBase<UserInterests, UserInterests._Fields>, java.io.Serializable, Cloneable, Comparable<UserInterests> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserInterests");

  private static final org.apache.thrift.protocol.TField USER_INTERESTS_FIELD_DESC = new org.apache.thrift.protocol.TField("userInterests", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField JOB_FIELD_DESC = new org.apache.thrift.protocol.TField("job", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserInterestsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserInterestsTupleSchemeFactory());
  }

  public String userInterests; // required
  public String job; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_INTERESTS((short)1, "userInterests"),
    JOB((short)2, "job");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_INTERESTS
          return USER_INTERESTS;
        case 2: // JOB
          return JOB;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_INTERESTS, new org.apache.thrift.meta_data.FieldMetaData("userInterests", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.JOB, new org.apache.thrift.meta_data.FieldMetaData("job", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserInterests.class, metaDataMap);
  }

  public UserInterests() {
  }

  public UserInterests(
    String userInterests,
    String job)
  {
    this();
    this.userInterests = userInterests;
    this.job = job;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserInterests(UserInterests other) {
    if (other.isSetUserInterests()) {
      this.userInterests = other.userInterests;
    }
    if (other.isSetJob()) {
      this.job = other.job;
    }
  }

  public UserInterests deepCopy() {
    return new UserInterests(this);
  }

  @Override
  public void clear() {
    this.userInterests = null;
    this.job = null;
  }

  public String getUserInterests() {
    return this.userInterests;
  }

  public UserInterests setUserInterests(String userInterests) {
    this.userInterests = userInterests;
    return this;
  }

  public void unsetUserInterests() {
    this.userInterests = null;
  }

  /** Returns true if field userInterests is set (has been assigned a value) and false otherwise */
  public boolean isSetUserInterests() {
    return this.userInterests != null;
  }

  public void setUserInterestsIsSet(boolean value) {
    if (!value) {
      this.userInterests = null;
    }
  }

  public String getJob() {
    return this.job;
  }

  public UserInterests setJob(String job) {
    this.job = job;
    return this;
  }

  public void unsetJob() {
    this.job = null;
  }

  /** Returns true if field job is set (has been assigned a value) and false otherwise */
  public boolean isSetJob() {
    return this.job != null;
  }

  public void setJobIsSet(boolean value) {
    if (!value) {
      this.job = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_INTERESTS:
      if (value == null) {
        unsetUserInterests();
      } else {
        setUserInterests((String)value);
      }
      break;

    case JOB:
      if (value == null) {
        unsetJob();
      } else {
        setJob((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_INTERESTS:
      return getUserInterests();

    case JOB:
      return getJob();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_INTERESTS:
      return isSetUserInterests();
    case JOB:
      return isSetJob();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserInterests)
      return this.equals((UserInterests)that);
    return false;
  }

  public boolean equals(UserInterests that) {
    if (that == null)
      return false;

    boolean this_present_userInterests = true && this.isSetUserInterests();
    boolean that_present_userInterests = true && that.isSetUserInterests();
    if (this_present_userInterests || that_present_userInterests) {
      if (!(this_present_userInterests && that_present_userInterests))
        return false;
      if (!this.userInterests.equals(that.userInterests))
        return false;
    }

    boolean this_present_job = true && this.isSetJob();
    boolean that_present_job = true && that.isSetJob();
    if (this_present_job || that_present_job) {
      if (!(this_present_job && that_present_job))
        return false;
      if (!this.job.equals(that.job))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(UserInterests other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserInterests()).compareTo(other.isSetUserInterests());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserInterests()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userInterests, other.userInterests);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJob()).compareTo(other.isSetJob());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJob()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.job, other.job);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserInterests(");
    boolean first = true;

    sb.append("userInterests:");
    if (this.userInterests == null) {
      sb.append("null");
    } else {
      sb.append(this.userInterests);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("job:");
    if (this.job == null) {
      sb.append("null");
    } else {
      sb.append(this.job);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserInterestsStandardSchemeFactory implements SchemeFactory {
    public UserInterestsStandardScheme getScheme() {
      return new UserInterestsStandardScheme();
    }
  }

  private static class UserInterestsStandardScheme extends StandardScheme<UserInterests> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserInterests struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_INTERESTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userInterests = iprot.readString();
              struct.setUserInterestsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // JOB
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.job = iprot.readString();
              struct.setJobIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserInterests struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.userInterests != null) {
        oprot.writeFieldBegin(USER_INTERESTS_FIELD_DESC);
        oprot.writeString(struct.userInterests);
        oprot.writeFieldEnd();
      }
      if (struct.job != null) {
        oprot.writeFieldBegin(JOB_FIELD_DESC);
        oprot.writeString(struct.job);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserInterestsTupleSchemeFactory implements SchemeFactory {
    public UserInterestsTupleScheme getScheme() {
      return new UserInterestsTupleScheme();
    }
  }

  private static class UserInterestsTupleScheme extends TupleScheme<UserInterests> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserInterests struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetUserInterests()) {
        optionals.set(0);
      }
      if (struct.isSetJob()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetUserInterests()) {
        oprot.writeString(struct.userInterests);
      }
      if (struct.isSetJob()) {
        oprot.writeString(struct.job);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserInterests struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.userInterests = iprot.readString();
        struct.setUserInterestsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.job = iprot.readString();
        struct.setJobIsSet(true);
      }
    }
  }

}

