/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum VoError implements org.apache.thrift.TEnum {
  GeneralError(0),
  IncorrectParametrs(1),
  RegistrationAlreadyExist(2),
  NotAuthorized(3),
  IncorectLocationCode(4),
  IncorrectPassword(5);

  private final int value;

  private VoError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static VoError findByValue(int value) { 
    switch (value) {
      case 0:
        return GeneralError;
      case 1:
        return IncorrectParametrs;
      case 2:
        return RegistrationAlreadyExist;
      case 3:
        return NotAuthorized;
      case 4:
        return IncorectLocationCode;
      case 5:
        return IncorrectPassword;
      default:
        return null;
    }
  }
}
