/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmesteonline.be.thrift.utilityservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CounterType implements org.apache.thrift.TEnum {
  HOT_WATER(0),
  COLD_WATER(1),
  ELECTRICITY(2),
  ELECTRICITY_NIGHT(3),
  ELECTRICITY_DAY(4),
  GAS(5),
  OTHER(6);

  private final int value;

  private CounterType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CounterType findByValue(int value) { 
    switch (value) {
      case 0:
        return HOT_WATER;
      case 1:
        return COLD_WATER;
      case 2:
        return ELECTRICITY;
      case 3:
        return ELECTRICITY_NIGHT;
      case 4:
        return ELECTRICITY_DAY;
      case 5:
        return GAS;
      case 6:
        return OTHER;
      default:
        return null;
    }
  }
}
